---
apiVersion: v1
kind: Service
metadata:
  name: myservice
spec:
  selector:
    environment: in (production, qa)
  type: NodePort
  ports:
  - name: mynginx-http
    protocol: TCP
    port: 80
    targetPort: nginxweb
